### ISSUE TITLE
?assignRanks Clearing Automatically 

### ISSUE THREAD

**Issue by IGSevda** [Warthog710/Rankie#10]
The assigned ranks appear to be clearing overnight without any prompts from admins. Ranks must be reassigned every day for the bot to function. 

There are no prompts or commands from the bot to indicate why the ranks would become unassigned. This issue occurs regardless of whether a ?setManagedChannel has been used or not in the server. 

![ex_1](https://user-images.githubusercontent.com/88249885/127749291-1e3b7a71-f822-4139-b5d9-d4bbe1c470a9.png)
![ex_2](https://user-images.githubusercontent.com/88249885/127749296-df7148ed-3571-456e-b5a5-839489ca8076.png)

**Comment by Warthog710** [comment]
I can confirm this is not how the bot should be behaving. Ranks are saved in a JSON file with associations to a server ID, in no way should this be cleared without express instructions from the server owner or authorized moderator. However, I currently have the bot running in a private and public server with set ranks with this behavior not being shown. How are you modifying the ranks after creation? Do you have another bot on your server that is perhaps modifying the existing ranks?

Adding the bug label for now and I will investigate this issue when time allows.

**Comment by IGSevda** [comment]
> How are you modifying the ranks after creation? Do you have another bot on your server that is perhaps modifying the existing ranks?

Carlbot is an actively used bot in our server, however it has not been instructed to modify the ranks for M+ which Rankie is exclusively using.

**Comment by Warthog710** [comment]
I have added some potential fixes in a88727ff1a13ced49f7f7fbf745daf2fe084d276 and 7110105ff3634d6aff214e04ebfaf6b2e390ca49. Let me know if you are still experiencing problems.

Also note, this update probably destroyed existing ranks for servers so it will be necessary to reset your ranks again. Also, if this didn't fix it, try kicking the bot and letting it join again. Some of the code that I found not to work involved joining a server.

**Comment by Warthog710** [comment]
Ah, it seems storage on Heroku (where the bot is hosted) is ephemeral. This means that the files the bot uses to save ranks for servers are being deleted. That is an unforeseen problem. I will have a solution developed for that sometime in the near future.

**Comment by Warthog710** [comment]
This has been fixed in 2200a2cebfa7bb8935eb1222e7c2573958b06967. If you continue to experience issues please open up another issue with details on it.
