### ISSUE TITLE
Bot offline?

### ISSUE THREAD

**Issue by Cameroncodes92** [Warthog710/Rankie#16]
Hey there, Love the bot! Excellent work. 

Just in the last 24 hours, we have noticed the bot is unresponsive and offline? We installed it from discord direct link. Any sort of help or update would be perfect. https://imgur.com/a/RwhvrTy

Thank you.

**Comment by Warthog710** [comment]
Should be fixed now. Recently had some server issues with the hosting platform and had to migrate off of it. Been a few hiccups.
