### ISSUE TITLE
Rankie not assigning ranks or referencing database

### ISSUE THREAD

**Issue by Cameroncodes92** [Warthog710/Rankie#17]
See screenshots- 

![image](https://user-images.githubusercontent.com/54254173/212501411-6dbed8ed-464b-4702-b573-00d9f050ec08.png)
![image](https://user-images.githubusercontent.com/54254173/212501434-2bcffe30-dc38-4d61-ba10-33e8383e26be.png)

Thank you, its an excellent bot but has been throwing these errors for the last couple of days.

**Comment by Warthog710** [comment]
I will take a look. I recently ported the bot from PostgreSQL to MySQL due to a hosting platform change so I imagine it is related.

**Comment by Warthog710** [comment]
Should be fixed. Restarting the bot seems to have done the trick. I setup a rotating restart schedule to hopefully prevent this and automatically deal with it in the future. Reopen this issue if you continue to have problems.
