### ISSUE TITLE
Failed to set season due to a database error. Please try again later.

### ISSUE THREAD

**Issue by ap0xr** [Warthog710/Rankie#19]
when i try to set season with ?setSeason current

i get this message please help me: Failed to set season due to a database error. Please try again later.

**Comment by Warthog710** [comment]
I will take a look at this when I have time. May be a few days.

**Comment by Nelythia** [comment]
Hey, is there any update?

**Comment by Warthog710** [comment]
Apologies for the long wait. This issue has now been resolved. The bot should be operating as normal. Please open another issue if this problem persists.
